language: python
sudo: false
python:
  - 2.7
virtualenv:
  system_site_packages: true
env:
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=wx
addons:
  apt:
    packages:
    - python-vtk
    - python-qt4
    - python-qt4-gl
    - python-wxgtk2.8
    - python-imaging
    - python-pip
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bash travis-install-wx sh
install:
  - pip install -r travis-requirements.txt
  - python setup.py develop
script:
  # Running all tests in tvtk/tests and mayavi.
  - coverage erase
  - coverage run -p -m nose.core -v tvtk/tests
  - coverage run -p -m nose.core -v mayavi
  # Run the integration tests.
  - cd integrationtests/mayavi
  - coverage run --rcfile=../../.coveragerc -p run.py
  - cd ../../
  - cp integrationtests/mayavi/.coverage.* ./
  - coverage combine
after_success:
  - pip install codecov
  - codecov
