language: python
sudo: false
python:
  - 2.7_with_system_site_packages
  - 3.4
env:
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=wx
matrix:
  allow_failures:
    - python: 3.4
      env: ETS_TOOLKIT=wx
    - python: 3.4
      env: ETS_TOOLKIT=qt4
addons:
  apt:
    packages:
    - python-vtk
    - pyhton-qt4-dev
    - python-qt4
    - python-qt4-gl
    - python-imaging
    - python-pip
    - python-wxtools
    - ccache
    - cmake
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - pip install -r travis-ci-requirements.txt
install:
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" ]]; then python -m lib2to3 -w setup.py; fi
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" ]]; then python -m lib2to3 -w tvtk/setup.py; fi
  - python setup.py develop
before_script:
  - mkdir testrun
  - cp .coveragerc testrun/
  - cp travis-run-integration-tests.sh testrun/
  - cd testrun
script:
  - coverage erase
  - coverage run -p -m nose.core -v tvtk
  - coverage run -p -m nose.core -v mayavi
  - if [[ ${ETS_TOOLKIT} == "wx" ]]; then sh travis-run-integration-tests.sh; fi
  - coverage combine
after_success:
  - pip install codecov
  - codecov
