language: python
python:
  - 2.7
virtualenv:
  # This allows installing python-vtk using apt-get and being able to import it.
  system_site_packages: true
install:
  # nose is already installed
  - pip install cython
  - sudo apt-get install python-numpy
  - sudo apt-get install python-vtk
  # Test against the current master of traits, traitsui and enable
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
  - pip install git+http://github.com/enthought/apptools.git#egg=apptools
  - python setup.py develop
script:
  # Running all tests in chaco/tests and chaco/tests2
  - nosetests -v mayavi tvtk
notifications:
  email:
    - travis-ci@enthought.com
