language: python
sudo: false
python:
  - 2.7
virtualenv:
  system_site_packages: true
env:
  - VTK_VERSION=5.8 ETS_TOOLKIT=qt4
  - VTK_VERSION=5.8 ETS_TOOLKIT=wx
  - VTK_VERSION=6.3 ETS_TOOLKIT=qt4
  - VTK_VERSION=6.3 ETS_TOOLKIT=wx
  - VTK_VERSION=7.0 ETS_TOOLKIT=qt4
  - VTK_VERSION=7.0 ETS_TOOLKIT=wx
matrix:
  allow_failures:
    - env: VTK_VERSION=6.3 ETS_TOOLKIT=qt4
    - env: VTK_VERSION=6.3 ETS_TOOLKIT=wx
    - env: VTK_VERSION=7.0 ETS_TOOLKIT=qt4
    - env: VTK_VERSION=7.0 ETS_TOOLKIT=wx
addons:
  apt:
    packages:
    - python-vtk
    - python-pyside
    - python-qt4
    - python-qt4-gl
    - python-imaging
    - python-pip
    - python-wxtools
    - ccache
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - if [[ ${VTK_VERSION} == "6.3" ]]; then source travis_setup_vtk_6_3.sh; fi
  - if [[ ${VTK_VERSION} == "7.0" ]]; then source travis_setup_vtk_7_0.sh; fi
  # Print the VTK version
  - python -c "from __future__ import print_function; import vtk; print('VTK Version:', vtk.vtkVersion.GetVTKVersion())"
  - pip install -r travis-requirements.txt
  - python setup.py develop
script:
  - coverage erase
  - coverage run -p -m nose.core -v tvtk/tests
  - coverage run -p -m nose.core -v mayavi
  # Force the use of pyside for integrationtests as pyqt4's event loop hangs
  - if [[ ${ETS_TOOLKIT} == "qt4" ]]; then export QT_API=pyside; fi
  - sh travis-run-integration-tests.sh
  - coverage combine
after_success:
  - pip install codecov
  - codecov
