language: python
python:
  - 2.7
virtualenv:
  # This allows installing python-vtk using apt-get and being able to import it.
  system_site_packages: true
install:
  # nose is already installed
  - sudo apt-get install python-vtk
  - pip install Sphinx
  # Test against the current master of traits, traitsui and apptools
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
  - pip install git+http://github.com/enthought/apptools.git#egg=apptools
  - python setup.py develop
script:
  # Running all tests in tvtk/tests and mayavi.
  - python -m nose.core -v tvtk/tests
  - python -m nose.core -v mayavi
notifications:
  email:
    - travis-ci@enthought.com
