codecov:
  notify:
    require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: 40...100

    status:
      project: true
      changes: 
        enabled: false

  comment:
    enabled : false
