codecov:
  notify:
    require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: 40...100

    status:
      project: 
        enabled: yes
      changes: 
        enabled: no

  comment:
    layout: "uncovered"
    behavior: default 

