codecov:
  notify:
    require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: 40...100

    status:
      # Learn more at https://codecov.io/docs#yaml_default_commit_status
      project: true

  comment:
    layout: "uncovered"
    behavior: default 

